DB_URL = "mysql+pymysql://ljsyst02_adm:vinimalu121924@ljsystem.com.br/ljsyst02_compras?charset=utf8mb4"
APP_BASE_URL = "https://shopmanager.streamlit.app"
WHATSAPP_PROVIDER=ULTRAMSG
ULTRAMSG_INSTANCE=instance173813
ULTRAMSG_TOKEN=j4qixjsmbjafuzn7
WHATSAPP_DESTINATARIOS=5519996293600, 5519992084567
WHATSAPP_ENVIAR_PDF=SIM
